name: guardator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-121.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  get: 4.6.5
  path: ^1.8.2
  sprintf: ^6.0.2
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  #lint: 1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

