name: guard_cli
version: 1.0.0+1
publish_to: none
description: A command line tool for en/decryption.
environment:
  sdk: '>=2.19.0-121.0.dev <3.0.0'

dependencies:
  args: ^2.3.1
  encrypt: ^5.0.1
  path: ^1.8.2
  sprintf: ^6.0.2

dev_dependencies:
  lint: ^1.0.0
  test: ^1.21.5
